export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS'
export const GET_MESSEGES_SUCCESS = 'GET_MESSEGES_SUCCESS'
export const MESSEGE_SEND_SUCESS = 'MESSEGE_SEND_SUCESS'
export const IMAGE_MESSEGE_SEND = 'IMAGE_MESSEGE_SEND'